server.port=9054
spring.application.name=movie-service

# Primary DataSource Configuration
spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:6578/byteforce
spring.datasource.primary.username=hades
spring.datasource.primary.password=hades
spring.datasource.primary.driver-class-name=org.postgresql.Driver
spring.datasource.primary.jpa.hibernate.ddl-auto=update
spring.datasource.primary.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secondary DataSource Configuration
spring.datasource.secondary.jdbc-url=jdbc:postgresql://localhost:6579/byteforce_read
spring.datasource.secondary.username=hades
spring.datasource.secondary.password=hades
spring.datasource.secondary.driver-class-name=org.postgresql.Driver
spring.datasource.secondary.jpa.hibernate.ddl-auto=update
spring.datasource.secondary.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.elasticsearch.uris=http://localhost:9200

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=false
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG


spring.kafka.bootstrap-servers=localhost:9092

spring.data.redis.host=localhost
spring.data.redis.port=6379
cache.redis.ttl.default=7
cache.redis.ttl.movies=14
cache.redis.ttl.series=24
cache.redis.compression.enabled=true
cache.local.enabled=true
cache.local.maximum-size=10000
cache.local.ttl=10
cache.movie.default.ttl=60
cache.movie.popular.ttl=60

# Enable Prometheus endpoint
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.access=read_only
management.prometheus.metrics.export.enabled=true

# FlexyPool configuration
flexy-pool.metrics.reporter.log.enabled=true
flexy-pool.metrics.reporter.log.reportingInterval=30s
flexy-pool.metrics.reporter.micrometer.enabled=true
flexy-pool.jmx.enabled=true

# DataSource-Proxy Micrometer configuration
management.observations.datasource.enabled=true

spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.write-dates-as-timestamps=false

# Jaeger Configuration
otel.exporter.otlp.endpoint=http://localhost:4317
otel.service.name=${spring.application.name}
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.exporter.otlp.protocol=grpc
otel.logs.exporter=none

# Debezium Database Configuration
debezium.database.hostname=${SOURCE_DB_HOST:localhost}
debezium.database.port=${SOURCE_DB_PORT:6578}
debezium.database.user=${SOURCE_DB_USER:hades}
debezium.database.password=${SOURCE_DB_PASSWORD:hades}
debezium.database.dbname=${SOURCE_DB_NAME:byteforce}
debezium.database.server-name=${SERVER_NAME:byteforce_postgres_server}

# Offset storage
debezium.offset-storage-file=${OFFSET_STORAGE_FILE:/tmp/offsets.dat}

# CDC Configuration
cdc.topics.prefix=${CDC_TOPIC_PREFIX:dbsync}

# Resilience4j
resilience4j.circuitbreaker.instances.kafkaNotification.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.kafkaNotification.slidingWindowSize=5
resilience4j.circuitbreaker.instances.kafkaNotification.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.kafkaNotification.failureRateThreshold=50
resilience4j.circuitbreaker.instances.kafkaNotification.waitDurationInOpenState=10s