spring.application.name=movie-service
spring.datasource.url=jdbc:postgresql://localhost:5432/byteforce
spring.datasource.username=ssh
spring.datasource.password=ssh
spring.datasource.driver-class-name=org.postgresql.Driver

spring.elasticsearch.uris=http://localhost:9200

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
