spring.application.name=auth-service
server.port=9095

# Postgresql second sync database
spring.datasource.url=jdbc:postgresql://localhost:6579/byteforce_read
spring.datasource.username=hades
spring.datasource.password=hades
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.show_sql=false


spring.main.allow-bean-definition-overriding=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
services.user-service.url=http://localhost:9057

jwt.secret=13cebd527e8228b4f3cc4ed18e78a80df7d4fe693145b4f5fc44b8de6c2d7511b59d966b84e187ae9d2cf898e7e9def2579d63272de8764854e59836e2f2415a
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000