input {
    beats {
        port => 5044
    }
}

filter {
    if [message] =~ /^\{.*\}$/ {
        json {
            source => "message"
        }
    }

    if [container][name] {
        mutate {
            add_field => { "service_name" => "%{[container][name]}" }
        }
    }

    if [timestamp] {
        date {
            match => [ "timestamp", "ISO8601" ]
        }
    }

    if [message] =~ /(?i)(ERROR|WARN|INFO|DEBUG|TRACE|FATAL)/ {
        grok {
            match => { "message" => "?<log_level>(?i)ERROR|WARN|INFO|DEBUG|TRACE|FATAL)" }
        }
        mutate {
            uppercase => [ "log_level" ]
        }
    }

    mutate {
        remove_field => [ "agent", "ecs", "host", "input" ]
    }
}

output {
    hosts => ["elasticsearch:9200]
    index => "logs-%{+YYYY.MM.dd}"
}
