spring.application.name=rating-service

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=rating_user_byteforce
spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS
spring.cassandra.local-datacenter=dc1
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
# Axon configuration for Cassandra
axon.eventhandling.processors.tracking-event-processors=cassandra
axon.axonserver.enabled=false
axon.axonserver.servers=localhost:8124
axon.axonserver.context=default
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# Eventuate configuration
eventuate.database.schema=rating_user_byteforce
eventuate.local.cdc.db.url=cassandra://localhost:9042


movie.service.url=localhost:9054
user.service.url=localhost:9055

spring.docker.compose.enabled=false


spring.data.redis.host=localhost
spring.data.redis.port=6379
cache.redis.ttl.default=7
cache.redis.ttl.movies=14
cache.redis.ttl.series=24
cache.redis.compression.enabled=true
cache.local.enabled=true
cache.local.maximum-size=10000
cache.local.ttl=10
cache.movie.default.ttl=60
cache.movie.popular.ttl=60